spring:
    datasource:
        url: ${mysql.url}
        username: ${PICPAY_BANKING_WALLET_DB_LOGIN:root}
        password: ${PICPAY_BANKING_WALLET_DB_PASSWORD:root}
        driver-class-name: ${mysql.driver}
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL57InnoDBDialect
