mysql:
    url: ${PICPAY_BANKING_WALLET_DB_URL:jdbc:mariadb://localhost:8306/banking-wallet?useSSL=false&sessionVariables=character_set_client=utf8,character_set_results=utf8,character_set_connection=utf8,collation_connection=utf8_general_ci}
    driver: org.mariadb.jdbc.Driver